### ISSUE TITLE
求助！获取不到calculateInlineCompletions

### ISSUE THREAD

**Issue by fallingleaflun** [purocean/expose-github-copilot-http-api#1]
![image](https://github.com/purocean/expose-github-copilot-http-api/assets/32243069/46f39785-fc54-496e-b476-c3500905ed29)
你好，我在知乎上看到了你的这个项目，觉得挺有用的，于是clone了你的项目下来运行。之后提示我Copilot is not active or not be hacked，然后debug发现了这个对象是undefined。
ps.我不会js。

**Comment by purocean** [comment]
首先你需要安装 Github Copolit 插件（我安装的是 v1.137.557），并登录上；然后，你需要运行项目中的脚本，把 Gtihub Copolit 插件破解了，可以参考文章说明

**Comment by fallingleaflun** [comment]
我用的v1.137.0，破解了，也能调用api，但是返回结果
![image](https://github.com/purocean/expose-github-copilot-http-api/assets/32243069/064e09ee-0f68-4cf4-a527-981cc5f143e5)

**Comment by fallingleaflun** [comment]
我已更新到577版本并破解，但是返回了
![image](https://github.com/purocean/expose-github-copilot-http-api/assets/32243069/8a6b7cb2-30bd-4bc8-a3f7-d0c238e06d20)

**Comment by purocean** [comment]
把请求发出来看看？或许是因为语言或者文本长度太短等问题导致的

**Comment by fallingleaflun** [comment]
![image](https://github.com/purocean/expose-github-copilot-http-api/assets/32243069/edfed74c-1c36-4848-808c-63de4dead5ab)

**Comment by purocean** [comment]
我测试了一下说上下文太短了，多写一些东西可以

**Comment by purocean** [comment]
![image](https://github.com/purocean/expose-github-copilot-http-api/assets/7115690/fd4f9bbb-35d6-4f38-9d7b-4defd45d9c88)
另外检查一下有没有开启markdown支持

**Comment by fallingleaflun** [comment]
破案了，就是没开markdown支持，谢谢！！！！！！！！
